import "./globals.css";
import localFont from "next/font/local";
const switzer = localFont({
  src: [
    { path: "./fonts/Switzer-Black.otf", weight: "900", style: "normal" },
    { path: "./fonts/Switzer-Extrabold.otf", weight: "800", style: "normal" },
  ],
  variable: "--font-switzer",
  display: "swap",
  fallback: ["system-ui", "Arial"],
  preload: true,
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 2️⃣ استخدام الخط في الـ HTML
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${switzer.variable} antialiased`}>
      <body className="font-switzer">{children}</body>
    </html>

  );
}
